AllCops:
  DisplayCopNames: true
  SuggestExtensions: false
  NewCops: enable

Metrics/BlockLength:
  Max: 100
Style/MultilineMethodCallIndentation:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
