docker:
  image: yegor256/rultor-image:1.22.0
readers:
  - "urn:github:526301"
install: |
  sudo apt-get update
  sudo apt-get install -y pandoc
  mvn dependency:get -DgroupId=net.sf.saxon -DartifactId=Saxon-HE -Dversion=10.0
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
    pdd -f /dev/null
    bundle install
    bundle exec rake default[${tag}] upgrades[${tag}]
    bundle exec rake site[${tag}] validate_site[${tag}]
    cp -r target/site /tmp
    git checkout gh-pages
    for d in $(ls /tmp/site); do rm -rf $d; cp -r /tmp/site/$d .; git add $d; done
    git commit --allow-empty -m "${tag}"
merge:
  script: |-
    pdd -f /dev/null
    bundle install
    bundle exec rake
