install: |
  export GEM_HOME=~/.ruby
  export GEM_PATH=$GEM_HOME:$GEM_PATH
  sudo apt-get update
  sudo gem install pdd -v 0.20.5
  sudo apt-get install -y pandoc
  mvn dependency:get -DgroupId=net.sf.saxon -DartifactId=Saxon-HE -Dversion=9.8.0-8
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
    pdd -f /dev/null
    bundle install
    rake default[${tag}] upgrades[${tag}]
    rake site[${tag}] validate_site[${tag}]
    cp -r target/site /tmp
    git checkout gh-pages
    for d in $(ls /tmp/site); do rm -rf $d; cp -r /tmp/site/$d .; git add $d; done
    git commit --allow-empty -m "${tag}"
architect:
- g4s8
- yegor256
merge:
  script: |-
    pdd -f /dev/null
    bundle install
    rake
deploy:
  script: |-
    echo 'There is no such thing as deploy'
    exit -1
