---
name: rake
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  rake:
    name: rake
    strategy:
      matrix:
        os: [ubuntu-22.04]
        ruby: [3.2]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - run: mvn dependency:get -DgroupId=net.sf.saxon -DartifactId=Saxon-HE -Dversion=10.0
      - run: bundle update
      - run: bundle exec rake
